apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ecommerce-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: backend
            path: k8s/backend
            namespace: dev
          - name: frontend
            path: k8s/frontend
            namespace: dev

  template:
    metadata:
      name: "{{name}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: krishanu77/ecommerce-{{name}}
        argocd-image-updater.argoproj.io/semver: "true"
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-credentials
    spec:
      project: default

      source:
        repoURL: git@github.com:KrishanuMishra/ecommerce-k8s.git
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
